from sqlalchemy import Column, Integer, String
from sqlalchemy import ForeignKey
from sqlalchemy.orm import relationship
from models.base import Base
from models.timing_score import TimingScore


class Score(Base):
    __tablename__ = "score"

    id = Column(Integer, primary_key=True)
    score_a0010 = Column(Integer)
    score_a0020 = Column(Integer)
    score_a0050 = Column(Integer)
    score_a0100 = Column(Integer)
    score_a0200 = Column(Integer)
    score_a0500 = Column(Integer)
    score_a1000 = Column(Integer)
    score_a2000 = Column(Integer)
    score_a5000 = Column(Integer)
    score_a10 = Column(Integer)
    score_a20 = Column(Integer)
    best_move_a0010 = Column(String)
    best_move_a0020 = Column(String)
    best_move_a0050 = Column(String)
    best_move_a0100 = Column(String)
    best_move_a0200 = Column(String)
    best_move_a0500 = Column(String)
    best_move_a1000 = Column(String)
    best_move_a2000 = Column(String)
    best_move_a5000 = Column(String)
    best_move_a10 = Column(String)
    best_move_a20 = Column(String)
    best_move_score_a0010 = Column(Integer)
    best_move_score_a0020 = Column(Integer)
    best_move_score_a0050 = Column(Integer)
    best_move_score_a0100 = Column(Integer)
    best_move_score_a0200 = Column(Integer)
    best_move_score_a0500 = Column(Integer)
    best_move_score_a1000 = Column(Integer)
    best_move_score_a2000 = Column(Integer)
    best_move_score_a5000 = Column(Integer)
    best_move_score_a10 = Column(Integer)
    best_move_score_a20 = Column(Integer)
    best_move_score_diff_a0010 = Column(Integer)
    best_move_score_diff_a0020 = Column(Integer)
    best_move_score_diff_a0050 = Column(Integer)
    best_move_score_diff_a0100 = Column(Integer)
    best_move_score_diff_a0200 = Column(Integer)
    best_move_score_diff_a0500 = Column(Integer)
    best_move_score_diff_a1000 = Column(Integer)
    best_move_score_diff_a2000 = Column(Integer)
    best_move_score_diff_a5000 = Column(Integer)
    best_move_score_diff_a10 = Column(Integer)
    best_move_score_diff_a20 = Column(Integer)
    best_move_score_diff_category_a0010 = Column(Integer)
    best_move_score_diff_category_a0020 = Column(Integer)
    best_move_score_diff_category_a0050 = Column(Integer)
    best_move_score_diff_category_a0100 = Column(Integer)
    best_move_score_diff_category_a0200 = Column(Integer)
    best_move_score_diff_category_a0500 = Column(Integer)
    best_move_score_diff_category_a1000 = Column(Integer)
    best_move_score_diff_category_a2000 = Column(Integer)
    best_move_score_diff_category_a5000 = Column(Integer)
    best_move_score_diff_category_a10 = Column(Integer)
    best_move_score_diff_category_a20 = Column(Integer)

    score_b0010 = Column(Integer)
    score_b0020 = Column(Integer)
    score_b0050 = Column(Integer)
    score_b0100 = Column(Integer)
    score_b0200 = Column(Integer)
    score_b0500 = Column(Integer)
    score_b1000 = Column(Integer)
    score_b2000 = Column(Integer)
    score_b5000 = Column(Integer)
    score_b10 = Column(Integer)
    score_b20 = Column(Integer)
    best_move_b0010 = Column(String)
    best_move_b0020 = Column(String)
    best_move_b0050 = Column(String)
    best_move_b0100 = Column(String)
    best_move_b0200 = Column(String)
    best_move_b0500 = Column(String)
    best_move_b1000 = Column(String)
    best_move_b2000 = Column(String)
    best_move_b5000 = Column(String)
    best_move_b10 = Column(String)
    best_move_b20 = Column(String)
    best_move_score_b0010 = Column(Integer)
    best_move_score_b0020 = Column(Integer)
    best_move_score_b0050 = Column(Integer)
    best_move_score_b0100 = Column(Integer)
    best_move_score_b0200 = Column(Integer)
    best_move_score_b0500 = Column(Integer)
    best_move_score_b1000 = Column(Integer)
    best_move_score_b2000 = Column(Integer)
    best_move_score_b5000 = Column(Integer)
    best_move_score_b10 = Column(Integer)
    best_move_score_b20 = Column(Integer)
    best_move_score_diff_b0010 = Column(Integer)
    best_move_score_diff_b0020 = Column(Integer)
    best_move_score_diff_b0050 = Column(Integer)
    best_move_score_diff_b0100 = Column(Integer)
    best_move_score_diff_b0200 = Column(Integer)
    best_move_score_diff_b0500 = Column(Integer)
    best_move_score_diff_b1000 = Column(Integer)
    best_move_score_diff_b2000 = Column(Integer)
    best_move_score_diff_b5000 = Column(Integer)
    best_move_score_diff_b10 = Column(Integer)
    best_move_score_diff_b20 = Column(Integer)
    best_move_score_diff_category_b0010 = Column(Integer)
    best_move_score_diff_category_b0020 = Column(Integer)
    best_move_score_diff_category_b0050 = Column(Integer)
    best_move_score_diff_category_b0100 = Column(Integer)
    best_move_score_diff_category_b0200 = Column(Integer)
    best_move_score_diff_category_b0500 = Column(Integer)
    best_move_score_diff_category_b1000 = Column(Integer)
    best_move_score_diff_category_b2000 = Column(Integer)
    best_move_score_diff_category_b5000 = Column(Integer)
    best_move_score_diff_category_b10 = Column(Integer)
    best_move_score_diff_category_b20 = Column(Integer)

    move_id = Column(Integer, ForeignKey('move.id'))
    move = relationship("Move", back_populates="scores")

    timing_score = relationship("TimingScore", uselist=False, back_populates="score")

    def __repr__(self):
        return "<Score(" \
               "score_a='%d', " \
               "score_b='%d', " \
               ")>" % (
                self.score_a0100, self.score_b0100)

